### ISSUE TITLE
首页图片认真的吗……

### ISSUE THREAD

**Issue by cn-qlg** [synodriver/aioaria2#1]

**Comment by synodriver** [comment]
这个项目就是为了作为爬虫的一部分而存在的，因为我没有找到一个异步调用aria2的包……所以……总之有了这个，这样就可以随便下载磁力链接之类的了，并且大文件下载要比scrapy的filepipline更快更稳定……至于抓取目标……

**Comment by ODtian** [comment]
我直接好家伙

**Comment by synodriver** [comment]
哪来的涩图？
