### ISSUE TITLE
Client connection was closed

### ISSUE THREAD

**Issue by jw-star** [synodriver/aioaria2#18]
Is it because of the network delay?
```
 raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
![image](https://user-images.githubusercontent.com/48782751/182010273-f3e63c23-432f-4814-b0b8-ddf8f0d87bf6.png)

**Comment by synodriver** [comment]
It's a wrapper around aiohttp and looks like something happens to aiohttp websocket response.
