### ISSUE TITLE
How to write the client as a global object, which has a prompt method

### ISSUE THREAD

**Issue by jw-star** [synodriver/aioaria2#22]
How to write the client as a global object, which has a prompt method
This is how I do it now

![image](https://user-images.githubusercontent.com/48782751/204127041-d5e7babd-0d83-444d-b433-ff4139b34d82.png)

**Comment by jw-star** [comment]
要是可以有一个封装的单例对象，是最好的

**Comment by synodriver** [comment]
You should mark it with typing's grammar to let pycharm know its type, for instance, ```client: Aria2WebsocketClient```

**Comment by jw-star** [comment]
thanks

**Comment by synodriver** [comment]
Besides, I'm not recommend using a global client because some strange issue with ```asyncio```.

**Comment by jw-star** [comment]
> Besides, I'm not recommend using a global client because some strange issue with `asyncio`.

Is there a more reasonable way, I'm looking to improve my code

**Comment by synodriver** [comment]
Use a class to hold that client should be fine, for instance, [the one](https://github.com/synodriver/awsome_scrapy_utils/blob/master/pipelines/aria2.py) I'm using in scrapy, which avoid initializing before eventloop itself. Or you can use a global factory function.

**Comment by jw-star** [comment]
![image](https://user-images.githubusercontent.com/48782751/204183991-929453c6-0a61-4a05-9583-5e485b20f23a.png)
Create client is an async method, I don't know how to create class

**Comment by synodriver** [comment]
an async class method is ok.
