### ISSUE TITLE
Restart arai2, the callback will be repeated,

### ISSUE THREAD

**Issue by jw-star** [synodriver/aioaria2#23]
Restart arai2, the callback will be repeated, please take a look, is there any problem with the code

https://github.com/jw-star/aria2bot/blob/23857d898d863c5bc75067772dc52d7263610483/aria2client.py#L31

**Comment by synodriver** [comment]
Why did you remove callbacks on init？

**Comment by jw-star** [comment]
Callbacks are lost after aria2 restart

**Comment by jw-star** [comment]
What happens now is that aria2 restarts and the callback repeats

**Comment by jw-star** [comment]
So I'm wondering if it's the reason for the repeated registration of callbacks

**Comment by synodriver** [comment]
What does the restart mean？The rpc server or the client？

**Comment by jw-star** [comment]
arai2 server

**Comment by synodriver** [comment]
There is nothing I can do for the server side, this should be an issu about reconnect.... That's long story.

**Comment by jw-star** [comment]
Well, I just want to ask if there is a solution, if not, it won’t have a big impact

**Comment by synodriver** [comment]
Ok, let me explain why. To reconnect, you need to make a new websocket connection, and update the client's attribute, but there is already a background task awaiting the old connection. So reconnect is not that easy. I wonder if there is any solution to tell the background task stop awaiting the old one.

**Comment by jw-star** [comment]
Can websocket solve this problem if it can be reconnected

**Comment by synodriver** [comment]
The receiving loop is necessary for the current implementation, so switching from another library wonlt help.

**Comment by jw-star** [comment]
可能英文更适合表达代码 哈哈

**Comment by synodriver** [comment]
反正要搞的话，可能得对aiohttp开刀

**Comment by jw-star** [comment]
嗯，不好优化的话，也问题不大，就是得重启，目前来看，websockt服务端断开连接的情况，不好处理确实

**Comment by synodriver** [comment]
晚点看看，或者帮我搞个pr解决下

**Comment by jw-star** [comment]
哈哈，我不太熟websockt,我也学习下算是

**Comment by jw-star** [comment]
先这样，我也再看看

**Comment by synodriver** [comment]
要不用httpclient吧，去轮训就没这些问题了

**Comment by synodriver** [comment]
Aria2HttpClient就是

**Comment by synodriver** [comment]
不过轮训没法用callback，这些只有websocket才有

**Comment by jw-star** [comment]
还是最好用websockt的

**Comment by jw-star** [comment]
服务端断开连接，客户端不断重连，应该没啥问题
